version: '3'

services:
  # Application service layer
  admin_app:
    build:
      context: .
      dockerfile: docker/config/app/dev.Dockerfile
    image: wedevbr/admin_app
    env_file:
      - .env
    container_name: admin_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: "remote_host=${DOCKER_XDEBUG_PORT} remote_connect_back=0 remote_enable=1 idekey=PHPSTORM remote_port=9001 remote_autostart=1"
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - admin-network

  # Data persistence service layer
  admin_mysql:
    image: mysql:5.7.22
    env_file:
      - .env
    container_name: admin_db
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - admin_data:/var/lib/mysql
    networks:
      - admin-network

  # PhpMyAdmin service layer
  admin_pma:
    image: phpmyadmin/phpmyadmin
    container_name: admin_pma
    env_file:
      - .env
    ports:
      - "${DOCKER_PMA_PORT}:80"
    environment:
      PMA_HOST: ${DB_HOST}
      UPLOAD_LIMIT: 102400000
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - admin-network
    depends_on:
      - admin_mysql

  #Redis queue
  admin_redis:
    container_name: admin_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - admin-network
    volumes:
      - redis_data:/data

#Docker Networks
networks:
  admin-network:
    driver: bridge
#Volumes
volumes:
  admin_data:
    driver: local

  redis_data:

